import { Lato } from "next/font/google";
import "./globals.css";

// Importing the Lato Google Font
const lato = Lato({
  weight: ["100", "300", "400", "700"], // Specify weights you need
  subsets: ["latin"], // Load the required subset, e.g., latin
  variable: "--font-lato", // CSS variable to reference the font
});

export const metadata = {
  title: "Thiasil | Quality Silica",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
